# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public"

    filter_sets:
        'thumb':
            quality: 85
            filters:
                thumbnail  : { size : [360, 230], mode : outbound }


    