vich_uploader:
    db_driver: orm

    mappings:
        trick_image:
            uri_prefix: /media/tricks
            upload_destination: '%kernel.project_dir%/public/media/tricks'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        user_image:
            uri_prefix: /media/userPicture
            upload_destination: '%kernel.project_dir%/public/media/userPicture'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        trick_main:
            uri_prefix: /media/trickMain
            upload_destination: '%kernel.project_dir%/public/media/trickMain'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
