vich_uploader:
    db_driver: orm

    mappings:
        trick_image:
            uri_prefix: /media/tricks
            upload_destination: '%kernel.project_dir%/public/media/tricks'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
